name: SquanchyFlutter
description: Just like Squanchy, but in Flutter.

dependencies:
  cupertino_icons: ^0.1.1
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/ic_settings.png
    - assets/ic_schedule.png
    - assets/ic_search.png
    - assets/ic_favourites_unselected.png
    - assets/ic_schedule_unselected.png
    - assets/ic_venue_unselected.png
    - assets/ic_schedule_selected.png
    - assets/ic_venue_selected.png
    - assets/ic_favourites_selected.png
    - assets/nothing_here.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: League Spartan
      fonts:
        - asset: fonts/LeagueSpartan-Bold.otf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Light.ttf
          weight: 300
        - asset: fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
